"""Markdown renderer — the PR comment. This is the viral surface.

Designed to be readable at a glance in a GitHub PR: a clear verdict header,
one block per check with its standard mappings, and the transparent risk
breakdown so nobody has to trust a black box.
"""

from __future__ import annotations

from ..checks.base import Status
from ..engine import AssuranceReport

_ICON = {Status.PASS: "\u2705", Status.REVIEW: "\u26a0\ufe0f", Status.FAIL: "\u274c"}


def _verdict_line(report: AssuranceReport) -> str:
    v = report.verdict
    if v is Status.FAIL:
        return f"{_ICON[v]} **AGENT ASSURANCE FAILED**"
    if v is Status.REVIEW:
        return f"{_ICON[v]} **AGENT ASSURANCE — REVIEW RECOMMENDED**"
    return f"{_ICON[v]} **AGENT ASSURANCE PASSED**"


def _standards_line(result) -> str:
    if not result.standards:
        return ""
    parts = []
    for s in result.standards:
        tag = f"{s.framework}:{s.control}"
        if s.relation != "maps":
            tag += f" ({s.relation})"
        parts.append(tag)
    return "Standards: " + ", ".join(parts)


def to_markdown(report: AssuranceReport) -> str:
    m = report.manifest
    lines: list[str] = []
    lines.append("## \U0001f916 Agent Assurance")
    lines.append("")
    lines.append(_verdict_line(report))
    lines.append("")
    lines.append(f"**Agent:** `{m.agent.name}` v{m.agent.version}")
    fw = m.framework.name or "unknown"
    lines.append(f"**Framework:** {fw} · **Autonomy:** L{m.autonomy}")
    if report.sources:
        mode = "declared manifest verified against observed configuration" if report.declared else "observed configuration only (no manifest declared)"
        lines.append(f"**Mode:** scan — {mode}")
    lines.append("")

    for r in report.results:
        lines.append(f"### {_ICON[r.status]} {r.check_id} — {r.title} · {r.status.value}")
        lines.append("")
        lines.append(r.summary)
        lines.append("")
        for d in r.details:
            lines.append(f"- {d}")
        std = _standards_line(r)
        if std:
            lines.append("")
            lines.append(f"_{std}_")
        lines.append("")

    if report.sources:
        lines.append("<details><summary>Sources scanned</summary>")
        lines.append("")
        lines.append("| File | Kind | Status | Notes |")
        lines.append("|---|---|---|---|")
        for src in report.sources:
            status = "parsed" if src.supported else "detected, not supported"
            lines.append(f"| `{src.path}` | {src.kind} | {status} | {src.note} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if report.verdict is not Status.PASS:
        lines.append("---")
        lines.append("\u26a0\ufe0f **Human governance review recommended before merge.**")
        lines.append("")

    lines.append(
        "<sub>Generated by "
        "[agent-assurance](https://github.com/kunko-ai-labs/agent-assurance) · "
        "transparent, rule-based, no LLM in the scoring path.</sub>"
    )
    return "\n".join(lines)
